ModelBindFaultSample/Models/Bird.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ModelBindFaultSample.Models
{
    public class Bird
    {
        [Key]
        public int BirdId { get; set; }

        public string EnglishName { get; set; }

        public DateTime CreationDate { get; set; }
    }
}

ModelBindFaultSample/Models/ErrorViewModel.cs
using System;

namespace ModelBindFaultSample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ModelBindFaultSample/Models/ModelStateErrorsExtensions.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace ModelBindFaultSample.Models
{
    public static class ModelStateErrorsExtensions
    {
        public static string GetModelStateErrorMessages(ModelStateDictionary ModelState)
        {
            string validationErrors = string.Join("; ",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

            return validationErrors;
        }
    }
}

ModelBindFaultSample/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace ModelBindFaultSample.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new ModelBindFaultSampleContext(
                serviceProvider.GetRequiredService<DbContextOptions<ModelBindFaultSampleContext>>()))
            {
               
                if (context.Bird.Any())
                {
                    return;
                }

                var birds = new Bird[]
                {
                    new Bird { EnglishName="SampleName1",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName2",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName3",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName4",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName5",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName6",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName7",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName8",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName9",CreationDate=DateTime.Now},
                    new Bird { EnglishName="SampleName10",CreationDate=DateTime.Now}
                };

                foreach (Bird b in birds)
                {
                    context.Bird.Add(b);
                }
                context.SaveChanges();
            }
        }
    }
}

ModelBindFaultSample/ViewModels/BirdIndexViewModel.cs
using ModelBindFaultSample.Models;
using System.Collections.Generic;

namespace ModelBindFaultSample.ViewModels
{
    public class BirdIndexViewModel
    {
        public bool ShowAll { get; set; }
        public bool ShowInTable { get; set; }
        public int SelectedBirdId { get; set; }
        //public List<Bird> BirdsList { get; set; }
        public PagedResult<Bird> BirdsList { get; set; }
        public IEnumerable<Bird> AllBirdsDropDownList { get; set; }
    }
}

ModelBindFaultSample/ViewModels/PagedResultBase.cs
using System;
using System.Collections.Generic;

namespace ModelBindFaultSample.ViewModels
{
    public abstract class PagedResultBase
    {
        public int CurrentPage { get; set; }
        public int PageCount { get; set; }
        public int PageSize { get; set; }
        public int RowCount { get; set; }

        public int FirstRowOnPage
        {
            get { return (CurrentPage - 1) * PageSize + 1; }
        }

        public int LastRowOnPage
        {
            get { return Math.Min(CurrentPage * PageSize, RowCount); }
        }
    }

    public class PagedResult<T> : PagedResultBase where T : class
    {
        public IList<T> Results { get; set; }

        public PagedResult()
        {
            Results = new List<T>();
        }
    }
}

ModelBindFaultSample/ViewModels/SortFilterBirdIndexOptions.cs
namespace ModelBindFaultSample.ViewModels
{
    public class SortFilterBirdIndexOptions
    {
        public int SelectedBirdId { get; set; }
        public bool ShowAll { get; set; }
        public bool ShowInTable { get; set; }
        public int Page { get; set; }
    }
}

ModelBindFaultSample/Controllers/BirdsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ModelBindFaultSample.Models;
using ModelBindFaultSample.ViewModels;

namespace ModelBindFaultSample.Controllers
{
    public class BirdsController : Controller
    {
        private const int pageSize = 2;
        private readonly ModelBindFaultSampleContext _context;

        public BirdsController(ModelBindFaultSampleContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(SortFilterBirdIndexOptions options)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelStateErrorsExtensions.GetModelStateErrorMessages(ModelState);
                return BadRequest(errors);
            }

            if (options.Page == 0)
            {
                options.Page = 1;
            }

            try
            {
                var viewModel = new BirdIndexViewModel();
                viewModel.AllBirdsDropDownList = await _context.Bird.ToListAsync();
                viewModel.BirdsList = await _context.Bird.AsNoTracking().GetPaged(options.Page, pageSize);
                viewModel.ShowAll = options.ShowAll;
                viewModel.ShowInTable = options.ShowInTable;
                return View(viewModel);
            }
            catch (Exception ex)
            {
                return NotFound();
            }
        }

        

        // GET: Birds
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Bird.ToListAsync());
        //}
    }
}

ModelBindFaultSample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ModelBindFaultSample.Models;

namespace ModelBindFaultSample.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ModelBindFaultSample/ViewComponents/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ModelBindFaultSample.ViewModels;
using System.Threading.Tasks;

namespace ModelBindFaultSample.ViewComponents
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

ModelBindFaultSample/Views/Birds/Index.cshtml
@model BirdIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Birds Index</h2>

<form id="sort-filter-form" class="form-horizontal">
    <div class="form-group">
        <div class="col-sm-4">
            @Html.DropDownListFor(m => m.SelectedBirdId,
                 new SelectList(Model.AllBirdsDropDownList, "BirdId", "EnglishName"),
                       new
                       {
                           @class = "form-control selectpicker-showtick",
                           title = "Choose a bird species...",
                           data_live_search = "true",
                           data_show_subtext = "true",
                           onchange = "this.form.submit()"
                       })
        </div>
        <div class="col-sm-4">
            <div>
                <label class="control-label">Show All?</label>
                <input asp-for="ShowAll" type="checkbox" data-toggle="toggle" onchange="this.form.submit()" data-on="All birds" data-off="Common birds">
            </div>
        </div>
        <div class="col-sm-4">
            <div>
                <label class="control-label">Show in Table?</label>
                <input asp-for="ShowInTable" type="checkbox" data-toggle="toggle" onchange="this.form.submit()" data-on="Table" data-off="Thumbnails list">
            </div>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Creation Date
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BirdsList.Results)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BirdId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EnglishName)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    @(await Component.InvokeAsync<PagerViewComponent>(Model.BirdsList))
</div>

ModelBindFaultSample/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ModelBindFaultSample/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ModelBindFaultSample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ModelBindFaultSample/Views/Shared/Components/Pager/Default.cshtml
@model PagedResultBase
@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
        //foreach (var keyValue in request.Query[key])
        //{
        //    urlTemplate += "&" + key + "=" + keyValue;
        //}
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);
}

<div class="row">
    <div class="col-md-4 col-sm-4 items-info">
        Items @Model.FirstRowOnPage to @Model.LastRowOnPage of @Model.RowCount total
    </div>
    <div class="col-md-8 col-sm-8">
        @if (Model.PageCount > 1)
        {
            <ul class="pagination pull-right">
                <li><a href="@urlTemplate.Replace("{0}", "1")">&laquo;</a></li>
                @for (var i = startIndex; i <= finishIndex; i++)
                {
                    @if (i == Model.CurrentPage)
                    {
                        <li><span>@i</span></li>
                    }
                    else
                    {
                        <li><a href="@urlTemplate.Replace("{0}", i.ToString())">@i</a></li>
                    }
                }
                <li><a href="@urlTemplate.Replace("{0}", Model.PageCount.ToString())">&raquo;</a></li>
            </ul>
        }
    </div>
</div>

ModelBindFaultSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelBindFaultSample</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css" crossorigin="anonymous" type="text/css">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ModelBindFaultSample</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Birds" asp-action="Index">Birds</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ModelBindFaultSample</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <!--Bootstrap-select dependencies -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>